name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1.3.0
    - name: Test
      run: "cargo build --verbose && cargo test && cargo build --release && cargo bench"
